"""add_perf_indexes

Revision ID: 2b727c506450
Revises: c3d4e5f6a7b8
Create Date: 2026-06-15 23:00:47.134404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b727c506450'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'activity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'assignment'::character varying"))
    op.alter_column('activities', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_activity_answers_submission_id', table_name='activity_answers')
    op.drop_index('ix_aqc_question_id', table_name='activity_question_choices')
    op.drop_index('ix_activity_questions_activity_id', table_name='activity_questions')
    op.drop_index('ix_activity_submissions_activity_id', table_name='activity_submissions')
    op.drop_index('ix_activity_submissions_student_id', table_name='activity_submissions')
    op.drop_index('ix_att_records_session_id', table_name='attendance_records')
    op.drop_index('ix_att_records_student_id', table_name='attendance_records')
    op.alter_column('attendance_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_att_sessions_class_id', table_name='attendance_sessions')
    op.drop_index('ix_att_sessions_date', table_name='attendance_sessions')
    op.drop_index('ix_att_sessions_teacher_id', table_name='attendance_sessions')
    op.alter_column('classes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('modules', 'order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('modules', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.alter_column('student_module_reads', 'first_read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_module_reads', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_student_module_reads_module_id', table_name='student_module_reads')
    op.drop_index('ix_student_module_reads_student_id', table_name='student_module_reads')
    op.alter_column('student_section_assignments', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sse_student_id', table_name='student_subject_enrollments')
    op.drop_index('ix_sse_subject_id', table_name='student_subject_enrollments')
    op.alter_column('teacher_class_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('teacher_class_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_sse_subject_id', 'student_subject_enrollments', ['subject_id'], unique=False)
    op.create_index('ix_sse_student_id', 'student_subject_enrollments', ['student_id'], unique=False)
    op.alter_column('student_section_assignments', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_student_module_reads_student_id', 'student_module_reads', ['student_id'], unique=False)
    op.create_index('ix_student_module_reads_module_id', 'student_module_reads', ['module_id'], unique=False)
    op.alter_column('student_module_reads', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_module_reads', 'first_read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('modules', 'order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('classes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('ix_att_sessions_teacher_id', 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_index('ix_att_sessions_date', 'attendance_sessions', ['session_date'], unique=False)
    op.create_index('ix_att_sessions_class_id', 'attendance_sessions', ['class_id'], unique=False)
    op.alter_column('attendance_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_att_records_student_id', 'attendance_records', ['student_id'], unique=False)
    op.create_index('ix_att_records_session_id', 'attendance_records', ['session_id'], unique=False)
    op.create_index('ix_activity_submissions_student_id', 'activity_submissions', ['student_id'], unique=False)
    op.create_index('ix_activity_submissions_activity_id', 'activity_submissions', ['activity_id'], unique=False)
    op.create_index('ix_activity_questions_activity_id', 'activity_questions', ['activity_id'], unique=False)
    op.create_index('ix_aqc_question_id', 'activity_question_choices', ['question_id'], unique=False)
    op.create_index('ix_activity_answers_submission_id', 'activity_answers', ['submission_id'], unique=False)
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('activities', 'activity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'assignment'::character varying"))
    # ### end Alembic commands ###
